import { Order } from './types/order';

export const ORDERS: Order[] = [
  {
    id: '1',
    item: 'Order 1',
    details: 'Details about order 1',
    status: 'Pending',
    slug: 'order-1',
    date: '2024-07-01',
    items: [
      {
        id: 1,
        title: 'Project 1',
        slug: 'project-1',
        imagesUrl: ['url1'],
        price: 10.0,
        heroImage: require('../assets/images/i-phone-1.jpg'),
      },
      {
        id: 2,
        title: 'Project 2',
        slug: 'project-2',
        imagesUrl: ['url2'],
        price: 20.0,
        heroImage: require('../assets/images/head-set-1.jpg'),
      },
    ],
  },
  {
    id: '2',
    item: 'Order 2',
    details: 'Details about order 2',
    status: 'Completed',
    slug: 'order-2',
    date: '2024-07-02',
    items: [
      {
        id: 3,
        title: 'Project 3',
        slug: 'project-3',
        imagesUrl: ['url3'],
        price: 30.0,
        heroImage: require('../assets/images/head-set-1.jpg'),
      },
      {
        id: 4,
        title: 'Project 4',
        slug: 'project-4',
        imagesUrl: ['url4'],
        price: 40.0,
        heroImage: require('../assets/images/head-set-1.jpg'),
      },
    ],
  },
  {
    id: '3',
    item: 'Order 3',
    details: 'Details about order 3',
    status: 'Shipped',
    slug: 'order-3',
    date: '2024-07-03',
    items: [
      {
        id: 5,
        title: 'Project 5',
        slug: 'project-5',
        imagesUrl: ['url5'],
        price: 50.0,
        heroImage: require('../assets/images/head-set-1.jpg'),
      },
      {
        id: 6,
        title: 'Project 6',
        slug: 'project-6',
        imagesUrl: ['url6'],
        price: 60.0,
        heroImage: require('../assets/images/head-set-1.jpg'),
      },
    ],
  },
  {
    id: '4',
    item: 'Order 4',
    details: 'Details about order 4',
    status: 'InTransit',
    slug: 'order-4',
    date: '2024-07-04',
    items: [
      {
        id: 7,
        title: 'Project 7',
        slug: 'project-7',
        imagesUrl: ['url7'],
        price: 70.0,
        heroImage: require('../assets/images/head-set-1.jpg'),
      },
      {
        id: 8,
        title: 'Project 8',
        slug: 'project-8',
        imagesUrl: ['url8'],
        price: 80.0,
        heroImage: require('../assets/images/head-set-1.jpg'),
      },
    ],
  },
];
